# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: 'app/styles/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  # Extends
  extends-before-declarations: 2
  extends-before-mixins: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 2
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-ids: 2
  no-invalid-hex: 2
  no-misspelled-properties: 1
  no-mergeable-selectors: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-url-domains: 2
  no-warn: 2

  # Nesting
  nesting-depth: 2
  declarations-before-nesting: 2

  # Name Formats
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      ignore:
        # These are being ignored because the DOM elements are pulled in via
        # CKEditor and we cannot control the class names
        - 'cke_tabulation'
        - 'cke_editable'
  function-name-format: 2
  mixin-name-format: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false

  # Style Guide
  attribute-quotes: 2
  border-zero:
    - 2
    -
      convention: 'none'
  brace-style: 2
  clean-import-paths: 2
  empty-args:
    - 2
    -
      include: true
  hex-length:
    - 2
    -
      style: long
  hex-notation: 2
  indentation: 2
  leading-zero:
    - 2
    -
      include: true
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  zero-unit: 2

  # Inner Spacing
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
